###################################################
# default settings
# https://jekyllrb.com/docs/configuration/default/
###################################################
timezone: Asia/Seoul
exclude: ["gitignore", "CNAME", "Gemfile", "Gemfile.lock", "gulpfile.js", "package.json", "package-lock.json", "node_modules", ".idea", "toyseed.github.io.iml", "__module", "__root_markup"]
markdown: kramdown

permalink: pretty

title: toyseed's blog

collections:
  tag:
    output: true
    permalink: /tag/:name/

plugins:
  - jekyll-feed

# https://jekyllrb.com/docs/configuration/front-matter-defaults/
# The defaults key holds an array of scope/values pairs that define what defaults should be set for a particular file path, and optionally, a file type in that path.
defaults:
  - scope:
      # an empty string here means all files in the project
      path: ""
      # The different types that are available to you are pages, posts, drafts or any collection in your site
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "tag"
    values:
      layout: "tagpostlist"
  - scope:
      path: ""
    values:
      layout: "default"